### PR TITLE
Changes authority value in Msal.UserAgentApplication

### PR DESCRIPTION
**Pull request by drzackyll**

### CODE REVIEW

**Comment by adi130987** [comment]
@drzackyll we need to keep dev config for local testing. Also I added authority in the config object.

**Comment by adi130987** [comment]
@drzackyll we need to keep dev config for local testing. Also I added authority in the config object.

**Comment by adi130987** [comment]
@drzackyll we need to keep dev config for local testing. Also I added authority in the config object.

**Comment by adi130987** [comment]
@drzackyll we need to keep dev config for local testing. Also I added authority in the config object.

**Comment by adi130987** [comment]
@drzackyll we need to keep dev config for local testing. Also I added authority in the config object.

**Comment by drzackyll** [comment]
connects to unicef/sir-releases#200

**Pull request merged**
